{% set name = "mapgenerator" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mapgenerator-{{ version }}.tar.gz
  sha256: 29be3c1be4d5cb64d7a04bb9b921be3991bae8c1e56dbc0422a997495c5adc70

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cartopy
    - chart-studio
    - config
    - configargparse
    - lxml
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - plotly
    - python >={{ python_min }}

test:
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - mapgenerator
    - mapgenerator.plotting.timeseries
  commands:
    - pip check

about:
  home: https://pypi.org/project/MapGenerator
  summary: Map Generator is a tool that provides easy to use 2D plotting functions for Earth sciences datasets.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sloosvel
    - zklaus
